let password=prompt("Enter your new password")
let doublecheck=prompt("Enter your password again")
var result = password.localeCompare(doublecheck)
if (result==1)
  console.log("The passwords are not the same. ")
if(result==0)
  console.log("The passwords are the same. ")
